apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.24.0 (7c629530)
  creationTimestamp: null
  labels:
    io.kompose.network/estudo-network: "true"
    io.kompose.service: apigateway
  name: apigateway
spec:
  containers:
    - env:
        - name: EUREKA.CLIENT.SERVICEURL.DEFAULTZONE
          value: http://naming-server:8761/eureka
        - name: RABBIT_URI
          value: amqp://guest:guest@rabbit-mq:5672
        - name: SPRING.ZIPKIN.BASEURL
          value: http://zipkin-server:9411/
        - name: SPRING_RABBITMQ_HOST
          value: rabbit-mq
        - name: SPRING_ZIPKIN_SENDER_TYPE
          value: rabbit
      image: tiagobarbano/apigateway:0.0.1-SNAPSHOT
      name: apigateway
      ports:
        - containerPort: 8765
      resources:
        limits:
          cpu: 750m
          memory: "838860800"
        requests:
          cpu: 250m
          memory: "419430400"
  restartPolicy: OnFailure
status: {}
