apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.24.0 (7c629530)
  creationTimestamp: null
  labels:
    io.kompose.service: book-db
  name: book-db
spec:
  ports:
    - name: "3310"
      port: 3310
      targetPort: 3310
    - name: 3310-tcp
      port: 3310
      targetPort: 3310
  selector:
    io.kompose.service: book-db
status:
  loadBalancer: {}
