apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.24.0 (7c629530)
  creationTimestamp: null
  labels:
    io.kompose.network/estudo-network: "true"
    io.kompose.service: zipkin-server
  name: zipkin-server
spec:
  containers:
    - env:
        - name: RABBIT_URI
          value: amqp://guest:guest@rabbit-mq:5672
      image: openzipkin/zipkin:2.23.2
      name: zipkin-server
      ports:
        - containerPort: 9411
      resources:
        limits:
          cpu: 500m
          memory: "1048576e3"
        requests:
          cpu: 250m
          memory: "209715200"
  restartPolicy: OnFailure
status: {}
