apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.24.0 (7c629530)
  creationTimestamp: null
  labels:
    io.kompose.service: cambio-db
  name: cambio-db
spec:
  ports:
    - name: "3308"
      port: 3308
      targetPort: 3308
    - name: 3308-tcp
      port: 3308
      targetPort: 3308
  selector:
    io.kompose.service: cambio-db
status:
  loadBalancer: {}
