apiVersion: v1
kind: Service
metadata:
  name: naming-server
  labels:
    app: naming-server
spec:
  ports:
    - port: 8761
      targetPort: 8761
  selector:
    app: naming-server
  type: LoadBalancer