apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.24.0 (7c629530)
  creationTimestamp: null
  labels:
    io.kompose.network/estudo-network: "true"
    io.kompose.service: rabbit-mq
  name: rabbit-mq
spec:
  containers:
    - image: rabbitmq:3.8.14-management
      livenessProbe:
        exec:
          command:
            - curl
            - -f
            - http://localhost:15672
        failureThreshold: 5
        periodSeconds: 30
        timeoutSeconds: 10
      name: rabbit-mq
      ports:
        - containerPort: 5672
        - containerPort: 15672
      resources:
        limits:
          cpu: 500m
          memory: "629145600"
        requests:
          cpu: 250m
          memory: "419430400"
  restartPolicy: OnFailure
status: {}
